"""Check every numeric cell of the manuscript's generated LaTeX tables (tab_t2_*.tex).
Usage: python3 07_check_latex_tables.py <pickle from 01> <dir with tab_t2_*.tex> <qwen_analysis.json> <combined_analysis.json>
Expected values are recomputed here from the independently parsed responses (NumPy/SciPy only).
The three bootstrap intervals of tab_t2_main are the exception: they depend on the package's seeded
resampling, so they are read from the two analysis JSON files regenerated by the package code.
A cell passes when the printed number equals the expected value at the printed precision."""
import sys, re, json, pickle, os
from collections import Counter
import numpy as np
from scipy import stats
cases,num,D=pickle.load(open(sys.argv[1],'rb')); TDIR=sys.argv[2]
QJ=json.load(open(sys.argv[3])); GJ=json.load(open(sys.argv[4]))
ARMS=['A0','B0','FULL','SELF','AGG','S0','PL0']; FAULTS=['F1','F2','F3','F8','F10','F13','F14','F15']; RX=['C_'+f for f in FAULTS]
truth=lambda c: cases[c]['true_label']
def rxs(c,dom): return RX if dom=='normal' else (['C_'+truth(c)] if dom=='own' else [r for r in RX if r!='C_'+truth(c)])
def sc(m,c,r,a):
    if a=='PROTO': return int((not num[c]['protoAbstain']) and num[c]['protoLabel']==truth(c))
    if a=='FedAvg': return int(num[c]['fedavgLabel']==truth(c))
    v=D[m][f'{c}|{r}|{a}']; return int(v['state']=='valid' and v['label']==truth(c))
def rv(m,c,dom,co): return sum(w*sum(sc(m,c,r,a) for r in rxs(c,dom))/len(rxs(c,dom)) for a,w in co.items())
def est(m,faults,dom,co):
    if dom=='normal': return 100*float(np.mean([rv(m,c,dom,co) for c in cases if truth(c)=='Normal']))
    return 100*float(np.mean([np.mean([rv(m,c,dom,co) for c in cases if truth(c)==f]) for f in faults]))
acc=lambda m,faults,dom,a: est(m,faults,dom,{a:1})
states=lambda m,a: Counter(v['state'] for k,v in D[m].items() if k.endswith('|'+a))
def numbers(cell_text):
    t=cell_text.replace('95\\%','').replace('\\times10^{','e').replace('{,}',',')
    out=[]
    for mth in re.finditer(r'[-+]?\d[\d,]*(?:\.\d+)?(?:e-?\d+)?',t):
        s=mth.group(0).replace(',','')
        mant=s.split('e')[0]; dec=len(mant.split('.')[1]) if '.' in mant else 0
        expo=int(s.split('e')[1]) if 'e' in s else 0
        out.append((float(s),0.5*10**(-dec)*10**expo*(1+1e-6)+1e-12*10**expo))
    return out
def rows(name):
    p=os.path.join(TDIR,name)
    if not os.path.exists(p): return None
    body=open(p,encoding='utf-8').read().split('\\midrule',1)[1].split('\\bottomrule')[0]
    return [r.strip() for r in body.replace('\\midrule','').split('\\\\') if '&' in r]
total=bad=0
def check(table,label,row,expected):
    global total,bad
    got=[x for cell in row.split('&')[1:] for x in numbers(cell)]
    if len(got)!=len(expected): bad+=1; total+=1; print(f'  MISMATCH {table} [{label}]: {len(got)} numbers printed, {len(expected)} expected'); return
    for (g,tol),e in zip(got,expected):
        total+=1
        if abs(g-e)>tol: bad+=1; print(f'  MISMATCH {table} [{label}]: printed {g}, recomputed {e:.6g}')
def table(name,expected_rows):
    r=rows(name)
    if r is None: print(f'{name}: FILE NOT FOUND'); return
    if len(r)!=len(expected_rows): print(f'{name}: {len(r)} rows printed, {len(expected_rows)} expected');
    before=bad
    for row,(label,exp) in zip(r,expected_rows): check(name,label,row,exp)
    print(f'{name}: {"ok" if bad==before else "see mismatches above"} ({len(r)} rows)')
P={'all':FAULTS,'noF1F8':[f for f in FAULTS if f not in('F1','F8')],'F1F8':['F1','F8']}
# arms
exp=[]
for a in ARMS:
    s=states('qwen',a); exp.append((a,[acc('qwen',FAULTS,'own',a),acc('qwen',FAULTS,'lu',a),acc('qwen',FAULTS,'normal',a),s['valid'],s['abstain'],s['invalid'],s['truncated']]))
for a in ('PROTO','FedAvg'): exp.append((a,[acc('qwen',FAULTS,'own',a),acc('qwen',FAULTS,'lu',a),acc('qwen',FAULTS,'normal',a)]))
table('tab_t2_arms.tex',exp)
table('tab_t2_supplement.tex',[(a,[acc('gptoss',FAULTS,'own',a),acc('gptoss',FAULTS,'lu',a),acc('gptoss',FAULTS,'normal',a),states('gptoss',a)['abstain']]) for a in ARMS])
table('tab_t2_allfaults.tex',[(dom+' '+f,[acc('qwen',[f],dom,a) for a in ARMS+['PROTO','FedAvg']]) for dom in('own','lu') for f in FAULTS])
# faults (with or without the two local-unseen columns)
r=rows('tab_t2_faults.tex'); exp=[]
for f in FAULTS:
    d=[rv('qwen',c,'own',{'FULL':1,'B0':-1}) for c in cases if truth(c)==f]
    e=[100*float(np.mean(d)),sum(x>0 for x in d),sum(x<0 for x in d),sum(x==0 for x in d)]
    if r and r[0].count('&')>=6: e+=[acc('qwen',[f],'lu','B0'),acc('qwen',[f],'lu','PROTO')]
    exp.append((f,e))
table('tab_t2_faults.tex',exp)
table('tab_t2_usage.tex',[(a,[float(np.mean([v['pt'] for k,v in D['qwen'].items() if k.endswith('|'+a)])),float(np.mean([v['ct'] for k,v in D['qwen'].items() if k.endswith('|'+a)]))]) for a in ARMS])
table('tab_t2_partitions.tex',[(p,[est('qwen',pf,'own',{'FULL':1,'B0':-1}),est('qwen',pf,'lu',{'B0':1,'PROTO':-1}),est('qwen',pf,'lu',{'B0':1,'FedAvg':-1})]) for p,pf in P.items()])
# main: Family A (Welch-Satterthwaite t), Family B (all 2^24 sign assignments, Holm), intervals from JSON
own=[c for c in cases if truth(c)!='Normal']; d={c:rv('qwen',c,'own',{'FULL':1,'B0':-1}) for c in own}
terms=[np.var([d[c] for c in own if truth(c)==f],ddof=1)/24 for f in FAULTS]; e=float(np.mean(list(d.values())))
se=np.sqrt(sum(terms))/8; df=sum(terms)**2/sum(t*t/23 for t in terms); tc=stats.t.ppf(.975,df)
def signflip(ints):
    sg=np.array(np.meshgrid(*[[-1,1]]*12)).reshape(12,-1).T; tot=((sg@np.array(ints[:12]))[:,None]+(sg@np.array(ints[12:]))[None,:]).ravel()
    return np.count_nonzero(np.abs(tot)>=abs(sum(ints)))/tot.size
raw={f:signflip([round(7*rv('qwen',c,'lu',{'B0':1,'PROTO':-1})) for c in sorted(cases) if truth(c)==f]) for f in('F1','F8')}
o=sorted(raw,key=raw.get); holm={o[0]:min(1,2*raw[o[0]])}; holm[o[1]]=max(holm[o[0]],raw[o[1]])
qb=[100*x for x in next(r for r in QJ['secondary'] if r['partition']=='all_faults' and r['domain']=='local_unseen' and r['contrast']=='B0-PROTO')['pointwiseBootstrap95']]
gj=lambda vis,con:[100*x for x in next(r for r in GJ['contrasts'] if r['model']=='gptoss' and r['domain']=='all_faults' and r['visibility']==vis and r['contrast']==con)['pointwise95']]
table('tab_t2_main.tex',[
 ('Family A',[100*e,acc('qwen',FAULTS,'own','FULL'),acc('qwen',FAULTS,'own','B0'),100*(e-tc*se),100*(e+tc*se),float(2*stats.t.sf(abs(e/se),df))]),
 ('Family B F1',[est('qwen',['F1'],'lu',{'B0':1,'PROTO':-1}),acc('qwen',['F1'],'lu','B0'),acc('qwen',['F1'],'lu','PROTO'),holm['F1']]),
 ('Family B F8',[est('qwen',['F8'],'lu',{'B0':1,'PROTO':-1}),acc('qwen',['F8'],'lu','B0'),acc('qwen',['F8'],'lu','PROTO'),holm['F8']]),
 ('B0-PROTO all',[est('qwen',FAULTS,'lu',{'B0':1,'PROTO':-1}),acc('qwen',FAULTS,'lu','B0'),acc('qwen',FAULTS,'lu','PROTO')]+qb),
 ('gpt-oss FULL-B0',[est('gptoss',FAULTS,'own',{'FULL':1,'B0':-1}),acc('gptoss',FAULTS,'own','FULL'),acc('gptoss',FAULTS,'own','B0')]+gj('own','FULL-B0')),
 ('gpt-oss B0-PROTO',[est('gptoss',FAULTS,'lu',{'B0':1,'PROTO':-1}),acc('gptoss',FAULTS,'lu','B0'),acc('gptoss',FAULTS,'lu','PROTO')]+gj('local_unseen','B0-PROTO'))])
def role(c,r): return 'normal' if truth(c)=='Normal' else ('own' if r=='C_'+truth(c) else 'lu')
exp=[]
for a in ARMS:
    cnt=Counter(role(*k.split('|')[:2]) for k,v in D['qwen'].items() if k.endswith('|'+a) and v['state']=='valid' and v['label']==k.split('|')[1][2:])
    exp.append((a,[cnt['own'],cnt['lu'],cnt['normal']]))
table('tab_t2_ownlabels.tex',exp)
print(f'cells checked: {total}, mismatches: {bad}')
