"""Assign every numeric token that 08b leaves outside its checked fragments to a statement,
with one source and one kind of evidence per token.

Usage: python3 11_classify_uncovered_numbers.py <uncovered.tsv from 08b> <classified.tsv> <list.md>

The rules below are pinned to the exact manuscript hash passed to the script. The script stops if a token matches no
rule or if a statement receives a number of tokens different from the expected one, so a change of
the manuscript cannot pass unnoticed.

Vocabulary (one value per token).
  source    package   the value can be checked with files of the public package
            private   checked in this review against a file of the private source files;
                      a reader of the package cannot repeat the check
            none      no source located
            n/a       an analysis choice or a statement taken from the literature
  evidence  declared             reported as configuration or as a statement (settings file, schema,
                                 list that assigns runs, text of the paper): what was intended
            observed-read        read in what the runs or the analysis produced (manifests generated
                                 by the runs, results files, insight records); not redone here
            observed-recomputed  recomputed or recounted from data in this review
            not-checked          nothing was checked
            n/a                  nothing to recompute
"""
import sys, csv, re, hashlib
from pathlib import Path
from collections import Counter
# id, expected tokens, sections, statement, source, evidence, note
ST = [
 ('S01', 5, 'I, IV, V, X', 'exploratory cohort: 96 runs, eight per fault, 32 Normal', 'private', 'observed-read',
  'runtime/p04/runs/p04_primary_001: 96 manifests generated by the runs, 8 for each of the eight faults and 32 Normal'),
 ('S02', 19, 'V', 'exploratory cohort: 267/448 and 266/448; difference +0.2 pp, CI [-6.3, +6.7]; 24/448; F1 52/56 vs 7/56; F8 4/56 vs 42/56', 'private', 'observed-read',
  'runtime/p10/session_02/RESULTS.json (coverage, classRates, contrasts[0]); all values coincide; not recomputed from the responses'),
 ('S03', 1, 'V', 'exploratory cohort: post-hoc own-class probe, +26.6 pp (FULL-B0, own-fault)', 'none', 'not-checked',
  'source not located. The same absolute value, -0.265625, appears in the exploratory results for a different contrast (B0-A0, local-seen): the author should confirm which result the sentence refers to'),
 ('S04', 1, 'V', 'exploratory cohort: logistic regression, 74.7 % five-seed mean local-unseen accuracy', 'private', 'observed-read',
  'private development results file (not included) (LIN, FEDAVG, local_unseen): mean 0.746875; the mean of the five listed per-seed values gives the same number'),
 ('S05', 1, 'III', "each client's own Normal pool has 40 windows (from five runs)", 'package', 'observed-read',
  'insight records: normal_windows_total is 40 over the full span in all eight insights. "Five runs" is a word, not a token: declared in the private development-pool manifest; development_streams.json omits the client of Normal runs'),
 ('S06', 2, 'III, IV', 'windows are 5 hours long', 'package', 'observed-recomputed',
  'case manifest: window_end_h - window_start_h = 5 for all 256 cases. The same length is checked by 08b in other sentences'),
 ('S07', 1, 'III', 'each window has 300 one-minute samples', 'package', 'declared',
  'verbalization_rules.json: samplingMinutes 1, windowHours 5, hence 300. Not checked against data'),
 ('S08', 1, 'III', '41 measured variables', 'package', 'declared',
  'verbalization_rules.json (calibration method: "41 measured variables"); also in the private FEATURE_SCHEMA.json'),
 ('S09', 1, 'III', '17 fields per variable', 'private', 'declared',
  'FEATURE_SCHEMA.json: components_per_variable 17'),
 ('S10', 4, 'III, VII', '697-component signatures', 'private', 'observed-recomputed',
  'the 640 development signatures have 697 columns (script 09). Declared in the package by the FedAvg recipe ("697 inputs"). Not observed on the test signatures, which are not available'),
 ('S11', 2, 'III, IV', 'faults begin at hour 25', 'private', 'declared',
  'src/data/simulation/sim_config.py (onset_h=25) and the paper. Observed-read only on the 64 fault runs of the exploratory cohort (activation at hour 25.00 in the manifests generated by the runs); not observed for the 256 test runs or the 80 development runs. The package shows where the analysed windows start, not when the fault is activated'),
 ('S12', 1, 'IV', 'runs last 65 hours', 'private', 'declared',
  'sim_config.py (stop_time_h=65). Consistent with the package: the last window ends at hour 65'),
 ('S13', 1, 'III', '30 retained observations (in "30 of 144")', 'package', 'observed-recomputed',
  'counted in the archived prompts; the same count is checked by 08b in another sentence'),
 ('S14', 1, 'III', '144 candidate observations', 'private', 'observed-read',
  'private development analysis facts file (not included), a product of the analysis, reports 144 candidates; they were not recounted'),
 ('S15', 1, 'III', 'gpt-oss service: 16,384-token context (and four concurrent requests)', 'none', 'not-checked',
  'stated only in the manuscript'),
 ('S16', 2, 'III', 'both inference services report vLLM 0.27.1', 'package', 'observed-read',
  'qwen_supplemental_accounting.json: value recorded by the primary service. Nothing in the package for gpt-oss. The two tokens are the two halves of one version string'),
 ('S17', 1, 'VI', "PROTO's class means, labels and counts occupy 27,234 bytes", 'private', 'observed-recomputed',
  'private prototype output file (not included): label, mean and count of the nine classes as compact JSON are 27,234 bytes'),
 ('S18', 3, 'IV, V', '95 % intervals', 'n/a', 'n/a', 'analysis choice; the analysis code uses the 0.975 quantile'),
 ('S19', 2, 'IV, VIII', 'no joint 0.05 claim across the two families', 'n/a', 'n/a', 'analysis choice'),
 ('S20', 1, 'VII', 'fault 1 and fault 8 both affect feed composition in stream 4', 'n/a', 'n/a', 'literature (Downs and Vogel, 1993); not re-read in this review'),
]
def rule(sec, num, ctx):
    if num in ('96', '32'): return 'S01'
    if sec.startswith('Exploratory antecedent'):
        if num == '95': return 'S18'
        if num == '+26.6': return 'S03'
        if num == '74.7': return 'S04'
        if num in ('267', '448', '266', '+0.2', '-6.3', '+6.7', '24', '52', '56', '7', '4', '42'): return 'S02'
    if num == '40' and 'own Normal pool of' in ctx: return 'S05'
    if num == '5' and ('Each 5-hour window has' in ctx or 'post-onset 5-hour window rule' in ctx): return 'S06'
    if num == '300': return 'S07'
    if num == '41': return 'S08'
    if num == '17': return 'S09'
    if num == '697': return 'S10'
    if num == '25' and 'begin at hour' in ctx: return 'S11'
    if num == '65' and 'Runs last' in ctx: return 'S12'
    if num == '30' and '30 of' in ctx: return 'S13'
    if num == '144': return 'S14'
    if num == '16,384': return 'S15'
    if num in ('0.27', '1') and 'vLLM 0.27.1' in ctx: return 'S16'
    if num == '27,234': return 'S17'
    if num == '95': return 'S18'
    if num == '0.05': return 'S19'
    if num == '4' and 'stream' in ctx: return 'S20'
rows = list(csv.DictReader(open(sys.argv[1], encoding='utf-8'), delimiter='\t', quoting=csv.QUOTE_NONE))
MANUSCRIPT_SHA = hashlib.sha256(Path(sys.argv[4]).read_bytes()).hexdigest() if len(sys.argv)>4 else 'not supplied'
PACKAGE_REVISION = sys.argv[5] if len(sys.argv)>5 else 'not supplied'
by = {s[0]: s for s in ST}; got = Counter(); out = []; bad = []
for r in rows:
    sid = rule(r['section'], r['number'], r['context'])
    if sid is None: bad.append(r); continue
    got[sid] += 1; out.append((sid, by[sid][4], by[sid][5], r['section'], r['number'], r['context']))
for r in bad: print('NO RULE:', r['section'], '|', r['number'], '|', r['context'])
mism = [(s[0], s[1], got[s[0]]) for s in ST if got[s[0]] != s[1]]
for m in mism: print('COUNT DIFFERS: %s expected %d, found %d' % m)
print(f'tokens {len(rows)}; assigned {len(out)}; statements {len(ST)}; without rule {len(bad)}; statements with a different count {len(mism)}')
for key, label in ((4, 'source'), (5, 'evidence')):
    c = Counter(); 
    for s in ST: c[s[key]] += got[s[0]]
    print(label + ':', ', '.join(f'{k} {v}' for k, v in sorted(c.items(), key=lambda x: -x[1])))
cross = Counter()
for s in ST: cross[(s[4], s[5])] += got[s[0]]
for (a, b), v in sorted(cross.items(), key=lambda x: -x[1]): print(f'   {a:8s} {b:20s} {v:3d} tokens  ' + ' '.join(s[0] for s in ST if (s[4], s[5]) == (a, b)))
if bad or mism: sys.exit(1)
with open(sys.argv[2], 'w', encoding='utf-8') as f:
    f.write('statement\tsource\tevidence\tsection\tnumber\tcontext\n')
    for o in out: f.write('\t'.join(o) + '\n')
with open(sys.argv[3], 'w', encoding='utf-8') as f:
    f.write(f'''# Numeric statements not covered by `08b_check_text_claims_extended.py`

Manuscript snapshot: SHA-256 `{MANUSCRIPT_SHA}`. Package revision: `{PACKAGE_REVISION}`.
This file is written by `11_classify_uncovered_numbers.py`; edit the script, not this file.

`08b` finds 438 numeric tokens in the manuscript body. 387 lie inside a fragment whose numbers are
recomputed from the package. The {len(out)} tokens below lie outside. Each token is assigned to one statement and
has one source and one kind of evidence: `B11_numbers_outside_checked_fragments_classified.tsv`
lists them one per line.

Not in this list because they are not in the inventory: table cells (checked by script 07), the figure,
the bibliography, numbers written as words outside a checked fragment, and names such as F1 or A0.

**Source**

- **package**: the value can be checked with files of the public package.
- **private**: checked in this review against a file of the private project files. The package
  does not contain that file, so a reader cannot repeat the check.
- **none**: no source located.
- **n/a**: an analysis choice or a statement taken from the literature.

**Evidence.** The category depends on how the value is used, not on the kind of file: a manifest can
be a specification or a product of the runs.

- **declared**: the value is reported as configuration or as a statement (a settings file, a schema, a
  list that assigns runs, the text of the paper). It says what was intended, not what happened in every run.
- **observed-read**: the value is read in what the runs or the analysis produced (manifests generated by
  the runs, results files, insight records). It was not redone in this review.
- **observed-recomputed**: the value was recomputed or recounted from data in this review.
- **not-checked**: nothing was checked.
- **n/a**: there is nothing to recompute.

| ID | Section | Statement | Tokens | Source | Evidence | Note |
|---|---|---|---|---|---|---|
''')
    for s in ST: f.write(f'| {s[0]} | {s[2]} | {s[3]} | {s[1]} | {s[4]} | {s[5]} | {s[6]} |\n')
    f.write('\nTotals by source and evidence:\n\n| Source | Evidence | Tokens | Statements |\n|---|---|---|---|\n')
    for (a, b), v in sorted(cross.items(), key=lambda x: -x[1]): f.write(f'| {a} | {b} | {v} | ' + ', '.join(s[0] for s in ST if (s[4], s[5]) == (a, b)) + ' |\n')
    f.write(f'\nTotal: {len(out)} tokens in {len(ST)} statements.\n\nTo keep the list current: after every change of the manuscript rerun `08b` with a sixth argument and then\nthis script. It stops when a token matches no rule or a statement changes its number of tokens.\n')
print('written:', sys.argv[2], sys.argv[3])
